[package]
name = "axioms"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
bevy_svg = "0.15.1"
g-code = "0.5.1"
num = "0.4.3"
plotters = "0.3.7"
roxmltree = "0.19.0"
svg2gcode = "0.3.3"
svgtypes = "0.13.0"
