#import "@preview/tiaoma:0.3.0"

#set page(
  paper: "a4",
  // The logo file was not provided, so the header is commented out.
  header: [
    #align(image("pinsky_logo_black.svg", width: 50pt), right)
  ],
  footer-descent: -20pt,
  footer: [
    #rect(
      stroke: none,
      inset: 0pt,
      stack(
        dir: ltr,
        spacing: 1fr,
        // QR code pointing to a new placeholder URL for this piece.
        tiaoma.qrcode("https://pinsky.studio/p/121608e8-3418-4a95-8b02-cba2a6d7602c"),
        align(text(datetime.today().display(), size: 14pt, weight: 600), bottom)
      )
    )
  ]
)

= * $= "Conformal_Twist_Mapping"(2)$ *

= Technical sheet

- *Year of production*: 2025
- *Technique*: Generative drawing plotted on 290g fine paper, archival pigment ink
- *Dimensions*: 50 × 50 cm

= Curatorial statement

This piece translates a foundational concept from complex analysis into a tangible, plotted artifact. The image, reminiscent of a magnetic dipole field, is generated by mapping a simple grid of lines through a complex function, revealing an elegant, emergent structure.

The transformation is governed by the function $f(z)$, which describes a field with a single pole, or singularity:

$
f(z) = 1 / (z + c), quad c = 0.01 + 0.01i
$

The work is defined by two core principles:

1. *The Pole and Singularity*
   The function possesses a single pole at $z = -c$. This point, where the function approaches infinity, acts as the center from which the entire structure of the field emanates, dictating the flow and curvature of every line.

2. *Conformal Mapping*
   As an analytic function, $f(z)$ is conformal everywhere except at its pole. This property ensures that the angles between intersecting lines are preserved from the original grid to the final drawing, resulting in the graceful, orthogonal curves that define the work's texture.

The work is an exploration of how simple, deterministic rules can generate profound structural complexity. It captures the invisible influence of a single point in the complex plane, rendering it as a serene pattern of ink on paper, where each line serves as a testament to the underlying mathematical logic.

#bibliography("references.bib", full: true)