#import "@preview/tiaoma:0.3.0"

#set page(
  paper: "a4",
  header: [
    #align(image("pinsky_logo_black.svg", width: 50pt), right)
  ],
  footer-descent: -20pt,
  footer: [
    #rect(
      stroke: none,
      inset: 0pt,
      stack(
        dir: ltr,
        spacing: 1fr,
        // QR code pointing to a new placeholder URL for this piece.
        tiaoma.qrcode("https://pinsky.studio/p/fe5bb12f-29de-426a-ab42-6f6ec7ca8174"),
        align(text(datetime.today().display(), size: 14pt, weight: 600), bottom)
      )
    )
  ]
)

= * $= "Conformal_Twist_Mapping"(3)$ *

= Technical sheet

- *Year of production*: 2025
- *Technique*: Generative drawing plotted on 290g fine paper, archival pigment ink
- *Dimensions*: 50 × 50 cm

= Curatorial statement

This work explores the emergence of high-order symmetry from a minimal set of mathematical rules. The image, a classic quatrefoil (four-leaf) pattern, is generated by a non-iterative conformal map that transforms the entire complex plane.

The function builds upon a single pole, which is then raised to a power to create the symmetrical lobes. The transformation is defined as:

$
f(z) = 1/( z + 0.1) dot e^(pi i)
$

The work is defined by two core principles:

1. *The Foundational Pole*
  The transformation is fundamentally defined by a single pole at $z = -0.1$. This singularity acts as a gravitational center, warping the fabric of the complex plane. All the visual structure—the curving of straight lines into elegant arcs—originates from the influence of this single, foundational point.

2. *Rigid Rotation*
  The multiplication by $e^(pi i)$ (which equals $-1$) applies a rigid 180-degree rotation to the entire inverted field. This final step reorients the structure in the plane but preserves its internal geometry, completing the transformation from a simple grid to the final, elegant form.

  
The piece is a study in structural emergence. It demonstrates how a simple element—a single pole—can be acted upon by a simple operation—exponentiation—to produce a form of intricate and unexpected beauty, bridging the gap between abstract formula and physical artifact.

#bibliography("references.bib", full: true)